<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-KE2SNMD2" failures="2" tests="8" name="Test" time="168.104" errors="0" timestamp="2025-02-02T19:53:51 IST">
  <testcase classname="testCases.TC_001account_reg_page" name="account_regirstationpage" time="6.261"/>
  <testcase classname="testCases.TC002_LoginTest" name="LoginVerify" time="2.822"/>
  <testcase classname="testCases.TC_003_Login_DataVerify" name="LoginVerify" time="10.781"/>
  <testcase classname="testCases.TC_003_Login_DataVerify" name="LoginVerify" time="13.304"/>
  <testcase classname="testCases.TC_003_Login_DataVerify" name="LoginVerify" time="6.72"/>
  <testcase classname="testCases.TC_003_Login_DataVerify" name="LoginVerify" time="11.515">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC_003_Login_DataVerify.LoginVerify(TC_003_Login_DataVerify.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- LoginVerify -->
  <testcase classname="testCases.TC_003_Login_DataVerify" name="LoginVerify" time="5.897"/>
  <testcase classname="testCases.TC_003_Login_DataVerify" name="LoginVerify" time="11.619">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC_003_Login_DataVerify.LoginVerify(TC_003_Login_DataVerify.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- LoginVerify -->
</testsuite> <!-- Test -->
